{
    "tensorflow.python.eager.core._status_to_exception": [],
    "tensorflow.python.eager.core._NotOkStatusException.__init__": [],
    "tensorflow.python.eager.core._NotOkStatusException.__str__": [],
    "tensorflow.python.eager.core._NotOkStatusException": [],
    "tensorflow.python.eager.core._FallbackException": [],
    "tensorflow.python.eager.core._SymbolicException": []
}